make ts better

diff --git a/.github/workflows/server-update-workflow.yml b/.github/workflows/server-update-workflow.yml
--- a/.github/workflows/server-update-workflow.yml
+++ b/.github/workflows/server-update-workflow.yml
@@ -22,10 +22,17 @@ jobs:
   test:
     runs-on: ubuntu-latest
     
+    # Ip and port arent really that secret but whatever.
     steps:
     - name: Send POST update request to watchdog
+      # Output of curl is hidden and we only say if something ever happened or nothing ever happened (as usual).
       run: |
-        curl \
+        if curl -s -f -o /dev/null \
             -v \
             -X POST \
-            -u ${{ vars.WATCHDOG_INSTANCE_NAME }}:${{ secrets.WATCHDOG_INSTANCE_API_TOKEN }} http://${{ secrets.WATCHDOG_IP_AND_PORT }}/instances/${{ vars.WATCHDOG_INSTANCE_NAME }}/update
+            -u "${{ vars.WATCHDOG_INSTANCE_NAME }}:${{ secrets.WATCHDOG_INSTANCE_API_TOKEN }} http://${{ secrets.WATCHDOG_IP_AND_PORT }}/instances/${{ vars.WATCHDOG_INSTANCE_NAME }}/update"; then
+          echo "Update request was successfully sent. This is not indicative of whether or not the server actually cares."
+        else
+          echo "Update request failed to sent. This is not indicative of whether or not the server actually cares."
+          exit 1
+        fi
